### PR TITLE
Fix lack of escaping functionality in echo $variable

### PR DESCRIPTION
**Pull request by w3bdesign**
You have not added sufficient sanitization of variables inside of your PHP code.

I have tried to add esc_url, esc_attr, esc_html and esc_html__ where I found room for improvement.

I have not tested the plugin extensively after applying my code, but feel free to take a look at my proposed changes and see if there is anything of value that can be implemented.

### CODE REVIEW

**Comment by w3bdesign** [comment]
@maximebj

**Comment by maximebj** [comment]
Thanks you ! I really appreciate your help. 

It was very a personnal project to learn how to make blocks, it was only for me but there are more and more users now. I have only little time to maintain this plugin and had a task to review all output and add proper sanitization. But you did it first, it's very cool ! I'll check this very soon and publish an update as soon as I can. 

Thank you very much again.

**Comment by w3bdesign** [comment]
@maximebj 

Any update on this? 

It's rather important to implement this seeing as it is a public plugin used by over 4000 people.

**Comment by maximebj** [comment]
I'll handle this, but remember that this is a side project and I don't have much time to work on this right now. I'll try to take time before the end of the month

**Pull request closed without merging**
